# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/repo

    steps:
      # use the github deploy key
      - add_ssh_keys:
          fingerprints:
            - "33:26:15:d0:f2:e8:4f:d7:26:8b:b1:9b:a2:1c:ca:f2"

      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            git clone git@github.com:modelica/fmi-standard.org.git

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Validate data
          command: |
            . venv/bin/activate
            python -m fmpy.cross_check.validate_vendor_repo ~/repo
            python -m fmpy.cross_check.result_tables ~/repo ~/repo/fmi-standard.org/_data

      - run:
          name: Push results to fmi-standard.org
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              git config --global user.email "circleci@fmi-standard"
              git config --global user.name "Circle CI"
              cd ~/repo/fmi-standard.org
              git add -u _data/cross-check/*.csv
              git commit -m "Adding cross-check results from CI (build $CIRCLE_BUILD_NUM)" || echo "No changes to commit"
              git push
            fi

      - store_artifacts:
          path: fmi-standard.org/_data
          destination: result-tables
