version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.1

    working_directory: ~/repo

    steps:

      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          name: Validate data
          command: |
            . venv/bin/activate
            pwd
            ls -al
            python --version
            python validate_repo.py
